//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBKursovaya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Научные_работы
    {
        public int ID_работы { get; set; }
        public string Название_работы { get; set; }
        public Nullable<int> ID_сотрудника { get; set; }
        public Nullable<System.DateTime> Дата_публикации { get; set; }
        public string Балл_эксперта { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
