//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBKursovaya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оборудование
    {
        public string Инвентарный_номер { get; set; }
        public string Отдел { get; set; }
        public string Производитель { get; set; }
        public string Модель { get; set; }
    
        public virtual Отделы Отделы { get; set; }
    }
}
